---
- hosts: nginx
  gather_facts: yes
  user: root
  vars_files:
    - "vars/{{ env }}.yml"

  roles:
      - nginx
      - app

- hosts: haproxy
  gather_facts: yes
  user: root
  vars_files:
    - "vars/{{ env }}.yml"

  roles:
    - certbot
    - haproxy
