- name: certbot_generate_crt | install certbot
  apt:
    name: certbot
    state: latest
    update_cache: true

- name: certbot_generate_crt | generate certificate 
  shell: "certbot certonly --standalone -d {{ app_name }}.{{ app_url_suffix }} --non-interactive --agree-tos -m muczos@candlebets.com"

- name: certbot_generate_crt | add hook for haproxy reload after cert renewal
  template:
    src: haproxy.sh.j2
    dest: /etc/letsencrypt/renewal-hooks/deploy/haproxy.sh
    owner: root
    group: root
    mode: '0750'

- name: certbot_generate_crt | combine key and crt for haproxy usage
  shell: "cat /etc/letsencrypt/live/{{ app_name}}.{{ app_url_suffix }}/fullchain.pem /etc/letsencrypt/live/{{ app_name}}.{{ app_url_suffix }}/privkey.pem > {{ cert_destination }}/{{ app_name}}.{{ app_url_suffix }}.pem"
  args:
    creates: "{{ cert_destination }}/{{ app_name}}.{{ app_url_suffix }}.pem"

- name: certbot_generate_crt | update certbot port for autorenwal
  template:
    src: cli.ini.j2
    dest: /etc/letsencrypt/cli.ini
    owner: root
    group: root
    mode: '0640'